export enum CONVERSATION_ACTION {
  LOAD_CONVERSATIONS = "LOAD_CONVERSATIONS",
  CREATE_CONVERSATION = "CREATE_CONVERSATION",
  DELETE_CONVERSATION = "DELETE_CONVERSATION",
  SEND_MESSAGE = "SEND_MESSAGE",
  DELETE_MESSAGE = "DELETE_MESSAGE",
  EDIT_MESSAGE = "EDIT_MESSAGE",
}
