export enum MESSAGE_LIST_CHANGE_EVENT {
  MESSAGE_SENT = "MESSAGE_SENT",
  CONVERSATION_CHANGED = "CONVERSATION_CHANGED",
  MESSAGE_DELETED = "MESSAGE_DELETED",
  MESSAGE_EDITED = "MESSAGE_EDITED",
}
